name: GodOfThunder
main: com.KoryuObihiro.bukkit.godofthunder.GodOfThunder
version: 0.1
authors: [KoryuObihiro]
description: |
    God of Thunder - unleash the storm within!
commands:
  godofthunder:
    aliases: [got]
    description: asdf
    usage: |
           /<command> 