name: GodOfThunder
main: com.KoryuObihiro.bukkit.godofthunder.GodOfThunder
version: 1.1
authors: [KoryuObihiro]
description: |
    God of Thunder - unleash the storm within!
commands:
  godofthunder:
    aliases: [got]
    description: Does anybody even use this?
    usage: |
           /<command> 
